### PR TITLE
Fix issue #11

### PR DESCRIPTION
**Pull request by pollusb**

### CODE REVIEW

**Review by TobiasPSP — COMMENTED** [review]
Wouldn’t we then also need a change in line 71 (falling back to slow PS method, adding -Filter $Filter)?

**Comment by pollusb** [comment]
I guess we should. But I feel that you would prefer not to. How would you solve this?

**Comment by TobiasPSP** [comment]
I very much appreciate your input. I am a bit busy currently so I can‘t review the code and the consequences of this change. It does seem to make total sense but I was wondering why I enumerated all files (w/o a filter), and whether there was possibly a reason. If you have verified the functionality, and all works fine, then I am more than happy to accept your request and add the code change :-)

**Comment by pollusb** [comment]
When using the fast method, with -Filter it now works beautifully. I will updated my fork's branch to filter to slow method and send you a new PR.

**Comment by TobiasPSP** [comment]
Many thanks that‘s awesome mate. Just added the merge.

**Pull request merged**
